@isTest 
public class TestForceForecastingBob {
    static testMethod void insertNewUser() {
       //User userToCreate = new User();
       
       //userToCreate.FirstName = 'Bob';
       //userToCreate.LastName  = 'TEST';
       //userToCreate.Email     = 'dvdkliubob@gmail.com';
       //userToCreate.Username  = 'sfdc-dreamerbob@gmail.com';
       //userToCreate.CommunityNickname  = 'sfdc-dreamer@gmail.com';       
       //userToCreate.Alias     = 'fatty';
       //userToCreate.ProfileId = '00e3600000161IV';
       
       //userToCreate.TimeZoneSidKey    = 'America/Denver';
       //userToCreate.LocaleSidKey      = 'en_US';
       //userToCreate.EmailEncodingKey  = 'UTF-8';
       //userToCreate.LanguageLocaleKey = 'en_US';
         //insert userToCreate;
         
         
         //User userToCreate1 = new User();
       
      // userToCreate1.FirstName = 'Boby';
       //userToCreate1.LastName  = 'TESTy';
       //userToCreate1.Email     = 'dvdklyiubob@gmail.com';
       //userToCreate1.Username  = 'sfdc-dreamerboby@gmail.com';
       //userToCreate1.CommunityNickname  = 'sfdc-dreamerbob@gmail.com';       
       //userToCreate1.Alias     = 'fatty1';
       //userToCreate1.ProfileId = '00e3600000161IZ';
       //userToCreate1.ProfileId = '00e3600000161IV';
       //userToCreate1.ProfileId = '00e3600000161IV';

       
       //userToCreate1.TimeZoneSidKey    = 'America/Denver';
       //userToCreate1.LocaleSidKey      = 'en_US';
       //userToCreate1.EmailEncodingKey  = 'UTF-8';
       //userToCreate1.LanguageLocaleKey = 'en_US';
         //insert userToCreate1;
       
       //  Application__c applicationToCreate = new Application__c ();
         
         //applicationToCreate.Sales_Path__c = 'Consumer Applicant';
         //applicationToCreate.OwnerId = userToCreate.id;
         //applicationToCreate.First_Name__c = 'Dude';
         
         //insert applicationToCreate;
         
         //applicationToCreate.OwnerId = userToCreate1.id;
         
         
        // update applicationToCreate;
         
         
         
         
         
         
       }}